#!/bin/bash
opts=()
while [[ $1 == -* ]]; do
	opts+=("$1")
	shift
done
if [[ $# -eq 0 ]]; then
	echo "Available robots (specify at least one on command line):"
	for f in examples/*; do
		[[ -x $f && $f != *.* ]] && echo ${f##*/}
	done
	exit 0
fi
./robotserver "${opts[@]}" &
serverpid=$!
sleep .5
export LD_LIBRARY_PATH=./lib:$LD_LIBRARY_PATH
for client; do
	[[ $client != */* ]] && client=./examples/$client
	$client &
done
wait $serverpid
