#define START	'g'
#define CYCLE	'c'
#define CANNON	'f'
#define SCAN	's'
#define DRIVE	'd'
#define LOC_X	'x'
#define LOC_Y	'y'
#define DAMAGE	'l'
#define SPEED	'v'
#define ELAPSED	'e'
#define GET_ALL	'a'
#define NAME	'n'
#define IMAGE	'i'

#define ERROR	'!'
#define OK	'k'
#define DEAD	'd'
